apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-activate2-fe
  labels:
    helm.sh/chart: activate2-fe-0.1.0
    app.kubernetes.io/name: activate2-fe
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: activate2-fe
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: activate2-fe
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 65534
      containers:
        - name: activate2-fe
          securityContext:
            {}
          image: "945109781822.dkr.ecr.us-east-1.amazonaws.com:master_f82992d"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
          env:
            - name: REACT_APP_BASE_BFF_API_URL
              value: https://a2bff.axonixtest.com/graphql/
            - name: REACT_APP_BASE_GEO_URL
              value: https://geo.stg.placecast.net/geo/
            - name: REACT_APP_BASE_BFF_AUTH_API_URL
              value: https://a2bff.axonixtest.com/auth
            - name: REACT_APP_OKTA_BASE_URL
              value: https://emodo.okta.com
            - name: REACT_APP_OKTA_CLIENT_ID
              value: 0oa9vik1b3q2Yr0IG5d7
            - name: REACT_APP_OKTA_REDIRECT_URL
              value: https://activate2-nfe.axonixtest.com/v1/auth/okta/oidc-callback
            - name: NODE_ENV
              value: stage